### ISSUE TITLE
Can it be an open source project? 

### ISSUE THREAD

**Issue by evandrocoan** [gamcoh/QuickEdit#2]
Searching through the repository I cannot find any mention to open source licence. By this project being on Github, I am allowed to fork it by the [Github TOS](https://help.github.com/articles/github-terms-of-service/) (Terms Of Service). However I am not allowed to create derivative works from it (pull requests). Meaning I cannot fork this repository, change its code and perform pull requests without the danger/liability of being prosecuted by violating the `All rights reserved` copyright granted by [berne convention](https://en.wikipedia.org/wiki/Berne_Convention) law.

___ 

Related issues:

1. https://github.com/SublimeText/LaTeXTools/issues/1175 Can it be an open source project?

**Comment by gamcoh** [comment]
Of course! But how can i create an open source license?

**Comment by evandrocoan** [comment]
As you are the only contributor to the project, you can choose any license you would like. I found the site:

1. https://choosealicense.com/licenses/

Which explains how to apply the Open Source License:

> How to apply this license

> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.

On that page, also on the apache own site you can find copy of the license:

1. http://www.apache.org/licenses/LICENSE-2.0.txt

You can download that file and commit it to your project. They recommend you to put a header on each of your source files, but it is too tedious keep editing and copying it. 

But GitHub has a built-in system to add licenses to your project. You can just follow their tutorial on:

1. https://help.github.com/articles/adding-a-license-to-a-repository/

1. ![image](https://user-images.githubusercontent.com/5332158/28540540-2003e098-708c-11e7-9347-8d3904e1c996.png)
